-- 코드를 입력하세요
WITH CTE(REST_ID, SCORE) AS (select REST_ID, ROUND(sum(REVIEW_SCORE)/count(REVIEW_SCORE),2) from REST_REVIEW group by REST_ID) 


SELECT REST_INFO.REST_ID, REST_INFO.REST_NAME, REST_INFO.FOOD_TYPE, REST_INFO.FAVORITES, REST_INFO.ADDRESS, CTE.SCORE as SCORE from REST_INFO JOIN CTE ON REST_INFO.REST_ID = CTE.REST_ID where ADDRESS like '서울%' order by SCORE desc , FAVORITES desc